import { Injectable, Logger } from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';
import PDFDocument from 'pdfkit';

@Injectable()
export class DocumentBuilderAgent {
  private readonly logger = new Logger(DocumentBuilderAgent.name);

  /**
   * Generates a PDF report for the given symbol and report data.
   * Enforces a constraint of at most one PDF report per symbol per calendar day.
   */
  async generatePdfReport(symbol: string, reportData: any): Promise<void> {
    const uppercaseSymbol = symbol.toUpperCase();
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    const dateStr = `${year}-${month}-${day}`;

    // Resolve reports directory at backend root
    const reportsDir = path.join(process.cwd(), 'reports_pdf');
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const fileName = `report_${uppercaseSymbol}_${dateStr}.pdf`;
    const filePath = path.join(reportsDir, fileName);

    // If PDF already exists for today, skip generation
    if (fs.existsSync(filePath)) {
      this.logger.log(`PDF report for ${uppercaseSymbol} on ${dateStr} already exists. Skipping PDF generation.`);
      return;
    }

    this.logger.log(`Generating PDF report for ${uppercaseSymbol} at ${filePath}`);

    const doc = new PDFDocument({
      margin: 50,
      size: 'A4',
      info: {
        Title: `${uppercaseSymbol} Stock Analysis Report`,
        Author: 'AI Stock Analyst Agent',
        Subject: `Financial Analysis for ${uppercaseSymbol}`,
        Keywords: `${uppercaseSymbol}, Analysis, AI, Finance`,
      },
    });

    const writeStream = fs.createWriteStream(filePath);
    doc.pipe(writeStream);

    try {
      // Helper function to draw headings
      const addHeading = (text: string) => {
        doc.moveDown(1.5);
        doc.font('Helvetica-Bold').fontSize(13).fillColor('#1E293B').text(text);
        doc.moveDown(0.4);
        doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E2E8F0').lineWidth(0.8).stroke();
        doc.moveDown(0.6);
      };

      // Helper function to draw subheadings
      const addSubheading = (text: string) => {
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#475569').text(text);
        doc.moveDown(0.3);
      };

      // Helper function to write bullet points
      const addBulletPoint = (label: string, desc?: string) => {
        doc.font('Helvetica-Bold').fontSize(9).fillColor('#1E293B').text('•  ' + label + ': ', { continued: !!desc });
        if (desc) {
          doc.font('Helvetica').fillColor('#334155').text(desc);
        } else {
          doc.text('');
        }
        doc.moveDown(0.25);
      };

      // Helper function to write standard text paragraph
      const addParagraph = (text: string) => {
        doc.font('Helvetica').fontSize(9.5).fillColor('#334155').lineGap(2).text(text, { align: 'justify' });
        doc.moveDown(0.6);
      };

      // --- PAGE 1: HEADER & KEY SUMMARY ---

      // Header Banner
      doc.rect(50, 40, 495, 45).fill('#1E293B');
      doc.fillColor('#F8FAFC');
      doc.font('Helvetica-Bold').fontSize(14).text('INSTITUTIONAL STOCK ANALYSIS REPORT', 65, 50);
      doc.font('Helvetica').fontSize(8.5).text(`GENERATED BY AI ANALYST AGENT  |  DATE: ${dateStr}`, 65, 68);

      doc.y = 105;

      // Symbol Title
      doc.font('Helvetica-Bold').fontSize(22).fillColor('#0F172A').text(uppercaseSymbol, 50, doc.y, { continued: true });
      const currentPrice = reportData.currentPrice || reportData.marketData?.price;
      if (currentPrice) {
        doc.font('Helvetica').fontSize(14).fillColor('#475569').text(`   $${currentPrice.toFixed(2)} USD`, { continued: false });
      } else {
        doc.text('');
      }
      doc.moveDown(0.5);

      // Suggestion Box
      const finalRating = reportData.finalRating || reportData.finalDecision?.finalRating || 'HOLD';
      const decisionSummary = reportData.finalDecision?.decisionSummary || 'Hold suggestion based on mixed signals.';
      let bg = '#F3F4F6';
      let textCol = '#374151';
      if (finalRating === 'BUY') { bg = '#E6F4EA'; textCol = '#065F46'; }
      else if (finalRating === 'SELL') { bg = '#FCE8E6'; textCol = '#991B1B'; }
      else if (finalRating === 'HOLD') { bg = '#FEF3C7'; textCol = '#92400E'; }
      else if (finalRating === 'WATCHLIST') { bg = '#F3E8FF'; textCol = '#6B21A8'; }
      else if (finalRating === 'AVOID') { bg = '#E5E7EB'; textCol = '#1F2937'; }

      const recBoxY = doc.y;
      doc.rect(50, recBoxY, 495, 50).fill(bg);
      doc.fillColor(textCol);
      doc.font('Helvetica-Bold').fontSize(12).text(`SUGGESTION: ${finalRating}`, 65, recBoxY + 12);
      doc.font('Helvetica').fontSize(9).text(decisionSummary, 65, recBoxY + 28, { width: 465, height: 16, ellipsis: true });
      doc.y = recBoxY + 60;

      // Score Matrix Card
      const scoreBoxY = doc.y;
      doc.rect(50, scoreBoxY, 495, 55).fill('#F8FAFC').stroke('#E2E8F0').lineWidth(0.5).stroke();
      doc.fillColor('#475569');
      
      const techScore = reportData.technicalScore ?? reportData.technicalAnalysis?.technicalScore ?? 'N/A';
      const fundScore = reportData.fundamentalScore ?? reportData.fundamentalAnalysis?.fundamentalScore ?? 'N/A';
      const newsScore = reportData.newsCatalystScore ?? reportData.newsAndCatalysts?.newsCatalystScore ?? 'N/A';
      const flowScore = reportData.institutionalFlowProxyScore ?? reportData.institutionalFlowProxy?.institutionalFlowProxyScore ?? 'N/A';

      doc.font('Helvetica-Bold').fontSize(8.5);
      
      // Technical Column
      doc.text('TECHNICAL SCORE', 65, scoreBoxY + 12);
      doc.font('Helvetica-Bold').fontSize(14).fillColor('#0F172A').text(String(techScore), 65, scoreBoxY + 24);

      // Fundamental Column
      doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#475569').text('FUNDAMENTAL SCORE', 185, scoreBoxY + 12);
      doc.font('Helvetica-Bold').fontSize(14).fillColor('#0F172A').text(String(fundScore), 185, scoreBoxY + 24);

      // News Column
      doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#475569').text('NEWS SENTIMENT', 315, scoreBoxY + 12);
      doc.font('Helvetica-Bold').fontSize(14).fillColor('#0F172A').text(String(newsScore), 315, scoreBoxY + 24);

      // Inst Flow Column
      doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#475569').text('INSTITUTIONAL FLOW', 445, scoreBoxY + 12);
      doc.font('Helvetica-Bold').fontSize(14).fillColor('#0F172A').text(String(flowScore), 445, scoreBoxY + 24);

      doc.y = scoreBoxY + 68;

      // Executive Summary
      addHeading('Executive Summary');
      const summaryText = reportData.executiveSummary?.summary || reportData.executiveSummary || 'No summary available.';
      addParagraph(summaryText);

      // Bullish/Bearish Factors
      const bullishFactors = reportData.executiveSummary?.bullishFactors || [];
      const bearishFactors = reportData.executiveSummary?.bearishFactors || [];

      if (bullishFactors.length > 0 || bearishFactors.length > 0) {
        doc.moveDown(0.3);
        const factorY = doc.y;
        
        // Bullish Column (Left)
        if (bullishFactors.length > 0) {
          doc.fillColor('#0F172A').font('Helvetica-Bold').fontSize(9.5).text('BULLISH FACTORS', 50, factorY);
          doc.y = factorY + 14;
          bullishFactors.slice(0, 3).forEach((factor: string) => {
            doc.font('Helvetica').fontSize(8.5).fillColor('#065F46').text(`+  ${factor}`, 50, doc.y, { width: 230 });
            doc.moveDown(0.2);
          });
        }

        // Bearish Column (Right)
        if (bearishFactors.length > 0) {
          doc.fillColor('#0F172A').font('Helvetica-Bold').fontSize(9.5).text('BEARISH FACTORS', 300, factorY);
          doc.y = factorY + 14;
          bearishFactors.slice(0, 3).forEach((factor: string) => {
            doc.font('Helvetica').fontSize(8.5).fillColor('#991B1B').text(`-  ${factor}`, 300, doc.y, { width: 230 });
            doc.moveDown(0.2);
          });
        }
      }

      // --- PAGE 2: DETAILED ANALYSIS ---
      doc.addPage();
      doc.y = 40;

      // Title Banner
      doc.rect(50, 40, 495, 25).fill('#1E293B');
      doc.fillColor('#F8FAFC');
      doc.font('Helvetica-Bold').fontSize(10).text(`${uppercaseSymbol} DETAILED ANALYSIS MODULES`, 65, 48);
      doc.y = 80;

      // Technical Analysis Section
      addHeading('Technical Indicator Analysis');
      const tech = reportData.technicalAnalysis;
      if (tech) {
        addSubheading(`Overall Bias: ${tech.overallBias || 'N/A'}  |  Stage: ${tech.trendStage || 'N/A'}  |  Pattern: ${tech.setupType || 'N/A'}`);
        if (tech.rsiAnalysis) addBulletPoint('Momentum (RSI)', tech.rsiAnalysis);
        if (tech.movingAverageAnalysis) addBulletPoint('Moving Averages', tech.movingAverageAnalysis);
        if (tech.macdAnalysis) addBulletPoint('MACD Trend', tech.macdAnalysis);
        if (tech.volumeAnalysis) addBulletPoint('Volume Flow', tech.volumeAnalysis);
        if (tech.vwapAnalysis) addBulletPoint('VWAP Relationship', tech.vwapAnalysis);
        
        if (tech.supportLevels && tech.supportLevels.length > 0) {
          addBulletPoint('Support Levels', tech.supportLevels.map((s: number) => `$${s.toFixed(2)}`).join(', '));
        }
        if (tech.resistanceLevels && tech.resistanceLevels.length > 0) {
          addBulletPoint('Resistance Levels', tech.resistanceLevels.map((r: number) => `$${r.toFixed(2)}`).join(', '));
        }
      } else {
        addParagraph('Detailed technical indicator snapshots are currently unavailable.');
      }

      // Fundamental Analysis Section
      addHeading('Fundamental Analysis & Valuation');
      const fund = reportData.fundamentalAnalysis;
      if (fund) {
        addBulletPoint('Valuation Rating', fund.valuationRating || 'N/A');
        if (fund.revenueGrowth) addBulletPoint('Revenue Growth', fund.revenueGrowth);
        if (fund.epsGrowth) addBulletPoint('Earnings Growth (EPS)', fund.epsGrowth);
        if (fund.profitMargin) addBulletPoint('Profit Margin', fund.profitMargin);
        
        const valuationMetrics = [];
        if (fund.peRatio) valuationMetrics.push(`P/E: ${fund.peRatio}`);
        if (fund.psRatio) valuationMetrics.push(`P/S: ${fund.psRatio}`);
        if (fund.pbRatio) valuationMetrics.push(`P/B: ${fund.pbRatio}`);
        if (fund.deRatio) valuationMetrics.push(`D/E: ${fund.deRatio}`);
        if (valuationMetrics.length > 0) {
          addBulletPoint('Valuation Ratios', valuationMetrics.join('  |  '));
        }
      } else {
        addParagraph('Fundamental metrics are currently unavailable.');
      }

      // News & Sentiment
      addHeading('News Catalysts & Market Sentiment');
      const news = reportData.newsAndCatalysts;
      if (news) {
        addSubheading(`Overall News Sentiment: ${news.overallNewsSentiment || 'NEUTRAL'}`);
        const keyCatalysts = news.keyCatalysts || reportData.keyCatalysts || [];
        if (keyCatalysts.length > 0) {
          doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#1E293B').text('Key Catalysts Detected:');
          doc.moveDown(0.2);
          keyCatalysts.slice(0, 3).forEach((c: string) => {
            doc.font('Helvetica').fontSize(8.5).fillColor('#334155').text(`•  ${c}`);
            doc.moveDown(0.15);
          });
        }
      } else {
        addParagraph('Recent news sentiment data is currently unavailable.');
      }

      // --- PAGE 3: TACTICAL SETUP & DISCLOSURE ---
      doc.addPage();
      doc.y = 40;

      // Title Banner
      doc.rect(50, 40, 495, 25).fill('#1E293B');
      doc.fillColor('#F8FAFC');
      doc.font('Helvetica-Bold').fontSize(10).text(`${uppercaseSymbol} EXECUTION PARAMETERS & RISK CONTROLS`, 65, 48);
      doc.y = 80;

      // Swing Trade Setup
      addHeading('Swing Trade Setup');
      const tactical = reportData.tacticalHorizonView;
      if (tactical) {
        // Param box
        const paramBoxY = doc.y;
        doc.rect(50, paramBoxY, 495, 55).fill('#F8FAFC').stroke('#E2E8F0').lineWidth(0.5).stroke();
        doc.fillColor('#475569');
        doc.font('Helvetica-Bold').fontSize(8);
        
        doc.text('ACCUMULATION ZONE', 65, paramBoxY + 12);
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#0F172A').text(tactical.accumulationZone || 'N/A', 65, paramBoxY + 24);

        doc.font('Helvetica-Bold').fontSize(8).fillColor('#475569').text('TARGET EXIT PRICE', 185, paramBoxY + 12);
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#065F46').text(tactical.targetPrice ? `$${tactical.targetPrice.toFixed(2)}` : 'N/A', 185, paramBoxY + 24);

        doc.font('Helvetica-Bold').fontSize(8).fillColor('#475569').text('STOP LOSS LIMIT', 315, paramBoxY + 12);
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#991B1B').text(tactical.stopLoss ? `$${tactical.stopLoss.toFixed(2)}` : 'N/A', 315, paramBoxY + 24);

        doc.font('Helvetica-Bold').fontSize(8).fillColor('#475569').text('RISK / REWARD RATIO', 445, paramBoxY + 12);
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#0F172A').text(tactical.riskRewardRatio || 'N/A', 445, paramBoxY + 24);

        doc.y = paramBoxY + 68;

        if (tactical.swingSetup?.chartAnalysis) {
          addBulletPoint('Setup Pattern', tactical.swingSetup.pattern || 'Consolidation');
          addBulletPoint('Timeframe Confirmation (1H/4H)', tactical.swingSetup.chartAnalysis);
        }
        if (tactical.entryTiming?.chartAnalysis) {
          addBulletPoint('Entry Timing Trigger', tactical.entryTiming.triggerCondition || 'N/A');
          addBulletPoint('Micro Timeframe Confirmation (5M/15M)', tactical.entryTiming.chartAnalysis);
        }
        if (tactical.riskMetrics) {
          addBulletPoint('Average True Range (ATR)', String(tactical.riskMetrics.atr ?? 'N/A'));
          addBulletPoint('VWAP Support Level', tactical.riskMetrics.vwapLocation || 'N/A');
        }
      } else {
        addParagraph('Tactical setup and key trade parameters are currently unavailable.');
      }

      // Risk Analysis & Position Sizing
      addHeading('Risk Analysis & Portfolio Guardrails');
      const risk = reportData.riskAnalysis;
      if (risk) {
        addSubheading(`Systemic Risk Level: ${risk.riskLevel || 'MEDIUM'}`);
        if (risk.positionSizingSuggestion) {
          addBulletPoint('Position Sizing Suggestion', risk.positionSizingSuggestion);
        }
        const topRisks = risk.topRisks || reportData.keyRisks || [];
        if (topRisks.length > 0) {
          doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#1E293B').text('Top Risk Factors:');
          doc.moveDown(0.2);
          topRisks.slice(0, 3).forEach((r: string) => {
            doc.font('Helvetica').fontSize(8.5).fillColor('#991B1B').text(`-  ${r}`);
            doc.moveDown(0.15);
          });
        }
      } else {
        addParagraph('Risk profiles and sizing parameters are currently unavailable.');
      }

      // Regulatory Disclaimer
      doc.moveDown(2);
      const disclaimerY = doc.y;
      doc.rect(50, disclaimerY, 495, 60).fill('#FEF2F2').stroke('#FCA5A5').lineWidth(0.5).stroke();
      doc.fillColor('#991B1B');
      doc.font('Helvetica-Bold').fontSize(8.5).text('IMPORTANT FINANCIAL DISCLAIMER AND DISCLAIMER OF LIABILITY', 65, disclaimerY + 10);
      doc.font('Helvetica').fontSize(7.2).fillColor('#7F1D1D').lineGap(1).text(
        'This AI analysis document is compiled for informational and educational purposes only. The system functions as a general data aggregator and does not constitute personalized investment, financial, tax, or legal advice. All trades, setups, ratings, or parameters suggested in this document are simulated outcomes of algorithmic models and carry high risks of capital loss. Past performance does not guarantee future market returns. Verify all data and consult with a licensed broker or certified financial adviser prior to committing real capital.',
        65,
        disclaimerY + 22,
        { width: 465, align: 'justify' }
      );

      // Finish PDF compilation
      doc.end();

      // Return when stream successfully finishes writing to file
      await new Promise<void>((resolve, reject) => {
        writeStream.on('finish', () => {
          this.logger.log(`PDF report successfully saved: ${filePath}`);
          resolve();
        });
        writeStream.on('error', (err) => {
          this.logger.error(`Error writing PDF file stream for ${uppercaseSymbol}: ${err.message}`);
          reject(err);
        });
      });

    } catch (err: any) {
      doc.destroy();
      this.logger.error(`Error inside PDF generation pipeline: ${err.message}`);
      throw err;
    }
  }
}
