import React, { useEffect, useState } from 'react';
// @ts-ignore
import { ViewTransition } from 'react';
import { reportsApi } from '../services/api';
import { Link } from 'react-router-dom';
import { RatingBadge, EmptyState, LoadingSpinner, ScoreBar } from '../components/ui';
import { FinalRating } from '../types';
import { Search, Filter } from 'lucide-react';

const RATINGS: FinalRating[] = ['BUY', 'HOLD', 'SELL', 'WATCHLIST', 'AVOID'];

const Reports: React.FC = () => {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterSymbol, setFilterSymbol] = useState('');
  const [filterRating, setFilterRating] = useState('');

  useEffect(() => { loadReports(); }, [filterSymbol, filterRating]);

  const loadReports = async () => {
    setLoading(true);
    try {
      const data = await reportsApi.getAll({
        symbol: filterSymbol || undefined,
        rating: filterRating || undefined,
        limit: 50,
      });
      setReports(data as any[]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 space-y-5 fade-in">
      <div>
        <h1 className="text-2xl font-bold text-slate-100">AI Reports</h1>
        <p className="text-sm text-slate-500 mt-0.5">Historical analyst reports generated by AI</p>
      </div>

      {/* Filters */}
      <div className="flex gap-3">
        <div className="relative flex-1 max-w-xs">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
          <input
            className="input pl-9 font-mono"
            value={filterSymbol}
            onChange={(e) => setFilterSymbol(e.target.value.toUpperCase())}
            placeholder="Filter by symbol"
            maxLength={10}
          />
        </div>
        <div className="relative">
          <Filter className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
          <select
            className="input pl-9 pr-8"
            value={filterRating}
            onChange={(e) => setFilterRating(e.target.value)}
          >
            <option value="">All Ratings</option>
            {RATINGS.map((r) => <option key={r} value={r}>{r}</option>)}
          </select>
        </div>
      </div>

      {loading ? (
        <div className="flex justify-center py-12"><LoadingSpinner size="lg" /></div>
      ) : reports.length === 0 ? (
        <EmptyState
          icon="📊"
          title="No reports yet"
          description="Run an analysis to generate your first AI report"
          action={<Link to="/analyze" className="btn-primary">Analyze Stock</Link>}
        />
      ) : (
        <div className="space-y-2">
          {reports.map((report) => (
            <Link
              key={report.id}
              to={`/stocks/${report.symbol}`}
              state={{ from: 'reports' }}
              className="card flex items-center justify-between hover:bg-slate-700/30 transition-all cursor-pointer"
            >
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 bg-slate-800 rounded-xl flex items-center justify-center font-bold text-brand-400 font-mono text-sm">
                  {report.symbol.slice(0, 2)}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    {/* @ts-ignore */}
                    <ViewTransition name={`stock-symbol-reports-${report.symbol}`} share="text-morph" default="none">
                      <span className="font-mono font-bold text-slate-100">{report.symbol}</span>
                    </ViewTransition>
                    <RatingBadge rating={report.finalRating} />
                  </div>
                  <div className="text-xs text-slate-500 mt-0.5 max-w-lg truncate">
                    {report.executiveSummary?.substring(0, 100)}...
                  </div>
                </div>
              </div>
              <div className="text-right shrink-0 ml-4">
                {report.currentPrice && (
                  <div className="text-sm font-mono text-slate-300">${report.currentPrice.toFixed(2)}</div>
                )}
                <div className="text-xs text-slate-600">{new Date(report.createdAt).toLocaleDateString()}</div>
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
};

export default Reports;
